/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/W1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.W1_1.geometry} material={materials['Material_001.004']} />
        <mesh geometry={nodes.W1_2.geometry} material={materials['Material_002.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/W1.glb')
