/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/finger.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature_007} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Feature001_006} />
    </group>
  )
}

useGLTF.preload('/finger.glb')
