/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/link7.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.node0.geometry}
        material={materials.Part__Mirroring_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node2.geometry}
        material={materials.Part__Mirroring002_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node3.geometry}
        material={materials.Part__Mirroring003_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node5.geometry}
        material={materials.Part__Mirroring005_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node6.geometry}
        material={materials.Part__Mirroring006_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node7.geometry}
        material={materials.Part__Mirroring007_004_001}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node1.geometry}
        material={materials.Part__Mirroring001_004_002}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.node4.geometry}
        material={materials.Part__Mirroring004_004_002}
        position={[0, 0.05, 0]}
        rotation={[0, -Math.PI / 4, 0]}
      />
    </group>
  )
}

useGLTF.preload('/link7.glb')
