/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/link0.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials.Part__Feature017_001} />
      <mesh geometry={nodes.node1.geometry} material={materials.Part__Feature022_001} />
      <mesh geometry={nodes.node2.geometry} material={materials.Part__Feature023_001} />
      <mesh geometry={nodes.node3.geometry} material={materials.Part__Feature019_001} />
      <mesh geometry={nodes.node4.geometry} material={materials.Part__Feature018_001} />
      <mesh geometry={nodes.node5.geometry} material={materials.Face636_001} />
      <mesh geometry={nodes.node6.geometry} material={materials.Shell001_001} />
      <mesh geometry={nodes.node7.geometry} material={materials.Shell002_001} />
      <mesh geometry={nodes.node8.geometry} material={materials.Shell_001} />
      <mesh geometry={nodes.node9.geometry} material={materials.Shell003_001} />
      <mesh geometry={nodes.node10.geometry} material={materials.Shell009_001} />
      <mesh geometry={nodes.node11.geometry} material={materials.Shell010_001} />
    </group>
  )
}

useGLTF.preload('/link0.glb')
