/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/W0.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.W0_1.geometry} material={materials['Material_001.009']} />
      <mesh geometry={nodes.W0_2.geometry} material={materials['Material_002.003']} />
      <mesh geometry={nodes.W0_3.geometry} material={materials['Material_003.001']} />
      <mesh geometry={nodes.W0_4.geometry} material={materials['Material_005.001']} />
    </group>
  )
}

useGLTF.preload('/W0.glb')
