/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/base_link.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.base_link_1.geometry} material={materials.Material_004} />
      <mesh geometry={nodes.base_link_2.geometry} material={materials['Material_001.007']} />
      <mesh geometry={nodes.base_link_3.geometry} material={materials.Material_003} />
      <mesh geometry={nodes.base_link_4.geometry} material={materials.Material_007} />
      <mesh geometry={nodes.base_link_5.geometry} material={materials.Material_005} />
      <mesh geometry={nodes.base_link_6.geometry} material={materials.Material_006} />
    </group>
  )
}

useGLTF.preload('/base_link.glb')
