/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/S0.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.S0_1.geometry} material={materials['Material_002.004']} />
      <mesh geometry={nodes.S0_2.geometry} material={materials['Material_003.002']} />
    </group>
  )
}

useGLTF.preload('/S0.glb')
