/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/forearm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Actor0_001.geometry} material={materials.blau_005} />
      <mesh geometry={nodes.Actor1.geometry} material={materials.Rohr_005} />
      <mesh geometry={nodes.Actor2.geometry} material={nodes.Actor2.material} />
      <mesh geometry={nodes.Actor3.geometry} material={nodes.Actor3.material} />
    </group>
  )
}

useGLTF.preload('/forearm.glb')
