/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shoulder.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['ActorShape0_0-Mesh023'].geometry} material={materials['verbindung.005']} />
      <mesh geometry={nodes['ActorShape0_0-Mesh023_1'].geometry} material={materials['Scheibe.003']} />
      <mesh geometry={nodes.Actor1.geometry} material={materials['blau.004']} />
    </group>
  )
}

useGLTF.preload('/shoulder.glb')
