/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/upperarm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['ActorShape0_0-Mesh024'].geometry} material={nodes['ActorShape0_0-Mesh024'].material} />
      <mesh geometry={nodes['ActorShape0_0-Mesh024_1'].geometry} material={nodes['ActorShape0_0-Mesh024_1'].material} />
      <mesh geometry={nodes.Actor1.geometry} material={nodes.Actor1.material} />
      <mesh geometry={nodes['ActorShape2_0-Mesh011'].geometry} material={nodes['ActorShape2_0-Mesh011'].material} />
      <mesh geometry={nodes['ActorShape2_0-Mesh011_1'].geometry} material={nodes['ActorShape2_0-Mesh011_1'].material} />
      <mesh geometry={nodes.Actor3.geometry} material={materials['Rohr.006']} />
      <mesh geometry={nodes.Actor4.geometry} material={nodes.Actor4.material} />
    </group>
  )
}

useGLTF.preload('/upperarm.glb')
