/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['ActorShape0_0-Mesh026'].geometry} material={materials.Scheibe_002} />
      <mesh geometry={nodes['ActorShape0_0-Mesh026_1'].geometry} material={materials.verbindung_002} />
      <mesh geometry={nodes.Actor1.geometry} material={materials.blau_002} />
    </group>
  )
}

useGLTF.preload('/wrist2.glb')
