/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['ActorShape0_0-Mesh025'].geometry} material={materials.Scheibe_001} />
      <mesh geometry={nodes['ActorShape0_0-Mesh025_1'].geometry} material={materials['verbindung_001.001']} />
      <mesh geometry={nodes.Actor1.geometry} material={materials['blau_001.001']} />
    </group>
  )
}

useGLTF.preload('/wrist1.glb')
