/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['ActorShape0_0-Mesh003'].geometry} material={materials.Rohr_007_001} />
      <mesh geometry={nodes['ActorShape0_0-Mesh003_1'].geometry} material={materials['SWMaterial-1_004_002_001']} />
    </group>
  )
}

useGLTF.preload('/wrist3.glb')
