/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/S1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.S1.geometry} material={materials['Material_001.006']} />
    </group>
  )
}

useGLTF.preload('/S1.glb')
