/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/robotiq_gripper_coupling.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Robotiq_Gripper_Coupling.geometry} material={nodes.Robotiq_Gripper_Coupling.material} />
    </group>
  )
}

useGLTF.preload('/robotiq_gripper_coupling.glb')
