/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/forearm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['node-shape0-name'].geometry} material={materials['SWMaterial-0.001']} />
      <mesh geometry={nodes['node-shape1-name'].geometry} material={materials['SWMaterial-1.001']} />
      <mesh geometry={nodes['node-shape2-name'].geometry} material={materials['SWMaterial-2.001']} />
      <mesh geometry={nodes['node-shape3-name'].geometry} material={materials['SWMaterial-3.001']} />
      <mesh geometry={nodes['node-shape4-name'].geometry} material={materials['SWMaterial-4.001']} />
    </group>
  )
}

useGLTF.preload('/forearm.glb')
