/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['node-shape0-name'].geometry} material={materials['SWMaterial-2_003']} />
    </group>
  )
}

useGLTF.preload('/wrist3.glb')
