/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur10Wrist1 from '../../Meshes/Ur10/wrist1.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {

  const { nodes, materials } = useGLTF('/wrist1.glb')
  return [
{type:'raw', geometry:nodes['node-shape0-name'].geometry, material:materials['SWMaterial-0_001']},
{type:'raw', geometry:nodes['node-shape1-name'].geometry, material:materials['SWMaterial-1_001']},
{type:'raw', geometry:nodes['node-shape2-name'].geometry, material:materials['SWMaterial-2_001']}
    ]
}

useGLTF.preload('/wrist1.glb')
