/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Box from '../../Meshes/Other/Box.glb';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Box);
  return [{type:'group',children:[{type:'raw', geometry:nodes.Body1.geometry,
  material:materials['Steel - Satin'], scale:[0.01, 0.01, 0.01]}],
  rotation:[Math.PI / 2, 0, 0]}]





}

useGLTF.preload(Box)
