/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Box.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Body1.geometry} material={materials['Steel - Satin']} scale={[0.01, 0.01, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Box.glb')
