/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Collision-Box.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['Collision-Box'].geometry} material={nodes['Collision-Box'].material} />
    </group>
  )
}

useGLTF.preload('/Collision-Box.glb')
