/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import LocationMarker from '../../Meshes/Other/LocationMarker.glb'

export default function Model(props) {

  const { nodes, materials } = useGLTF(LocationMarker)
  return [{type:'raw',geometry:nodes.LocationMarker.geometry, material:nodes.LocationMarker.material}

]
}

useGLTF.preload(LocationMarker)
