/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/MK2-Printer.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['MK2-Printer'].geometry} material={nodes['MK2-Printer'].material} />
    </group>
  )
}

useGLTF.preload('/MK2-Printer.glb')
