/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import OpenWaypointMarker from '../../Meshes/Other/OpenWaypointMarker.glb';

export default function Model(props) {

  const { nodes, materials } = useGLTF(OpenWaypointMarker)
  return [
{type:'raw', geometry:nodes.OpenWaypointMarker.geometry, material:nodes.OpenWaypointMarker.material}
]

}

useGLTF.preload(OpenWaypointMarker)
