/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/OpenWaypointMarker.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.OpenWaypointMarker.geometry} material={nodes.OpenWaypointMarker.material} />
    </group>
  )
}

useGLTF.preload('/OpenWaypointMarker.glb')
