/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./meshes/naoHead.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.NaoHead.material}
        geometry={nodes.NaoHead.geometry}
        position={[-0.22, -0.02, -1.6]}
      />
      <mesh
        material={materials.HeadPitchUV}
        geometry={nodes.HeadPitch001.geometry}
        position={[-0.14, 0.19, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  );
}

useGLTF.preload("/naoHead.glb");
