/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/base.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Base005.geometry} material={materials['Material_001.003']} />
      <mesh geometry={nodes.Base005_1.geometry} material={materials['Material_002.003']} />
    </group>
  )
}

useGLTF.preload('/base.glb')
