/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/upperarm.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={nodes.node0.material} />
      <mesh geometry={nodes.node1.geometry} material={nodes.node1.material} />
      <mesh geometry={nodes.node2.geometry} material={nodes.node2.material} />
      <mesh geometry={nodes.node3.geometry} material={nodes.node3.material} />
      <mesh geometry={nodes.node4.geometry} material={nodes.node4.material} />
      <mesh geometry={nodes.node5.geometry} material={nodes.node5.material} />
      <mesh geometry={nodes.node6.geometry} material={materials['Rohr.001']} />
      <mesh geometry={nodes.node7.geometry} material={nodes.node7.material} />
      <mesh geometry={nodes.node8.geometry} material={nodes.node8.material} />
      <mesh geometry={nodes.node9.geometry} material={nodes.node9.material} />
      <mesh geometry={nodes.node10.geometry} material={nodes.node10.material} />
      <mesh geometry={nodes.node11.geometry} material={nodes.node11.material} />
    </group>
  )
}

useGLTF.preload('/upperarm.glb')
