/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Ur3Upperarm from '../../Meshes/Ur3/upperarm.glb';

export default function Model(props) {
  
  const { nodes, materials } = useGLTF(Ur3Upperarm)
  return [
{type:'raw',geometry:nodes.node0.geometry, material:nodes.node0.material} ,
{type:'raw',geometry:nodes.node1.geometry, material:nodes.node1.material},
{type:'raw',geometry:nodes.node2.geometry, material:nodes.node2.material},
{type:'raw',geometry:nodes.node3.geometry, material:nodes.node3.material},
{type:'raw',geometry:nodes.node4.geometry, material:nodes.node4.material},
{type:'raw',geometry:nodes.node5.geometry, material:nodes.node5.material},
{type:'raw',geometry:nodes.node6.geometry, material:materials['Rohr.001']},
{type:'raw',geometry:nodes.node7.geometry, material:nodes.node7.material},
{type:'raw',geometry:nodes.node8.geometry, material:nodes.node8.material},
{type:'raw',geometry:nodes.node9.geometry, material:nodes.node9.material},
{type:'raw',geometry:nodes.node10.geometry, material:nodes.node10.material},
{type:'raw',geometry:nodes.node11.geometry, material:nodes.node11.material}

  ]
}

useGLTF.preload(Ur3Upperarm)
