/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import Ur3Wrist3 from '../../Meshes/Ur3/wrist3.glb';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Ur3Wrist3)
  return [

{type:'raw',geometry:nodes.node0.geometry,material:materials['Rohr.002']} ,
{type:'raw',geometry:nodes.node1.geometry,material:materials['verbindung.004']}

  ]
}

useGLTF.preload(Ur3Wrist3)
