/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials['blau.003']} />
      <mesh geometry={nodes.node1.geometry} material={nodes.node1.material} />
      <mesh geometry={nodes.node2.geometry} material={nodes.node2.material} />
    </group>
  )
}

useGLTF.preload('/wrist2.glb')
