/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Ur3Wrist2 from '../../Meshes/Ur3/wrist2.glb';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(Ur3Wrist2);
  return [

{type: 'raw', geometry:nodes.node0.geometry,material:materials['blau.003']},
{type: 'raw', geometry:nodes.node1.geometry, material:nodes.node1.material},
{type: 'raw', geometry:nodes.node2.geometry, material:nodes.node2.material} ]


}

useGLTF.preload(Ur3Wrist2)
