/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wrist3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.node0.geometry} material={materials['Rohr.002']} />
      <mesh geometry={nodes.node1.geometry} material={materials['verbindung.004']} />
    </group>
  )
}

useGLTF.preload('/wrist3.glb')
