/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/PEDESTAL.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.PEDESTAL.geometry} material={materials.Material_001} />
    </group>
  )
}

useGLTF.preload('/PEDESTAL.glb')
