/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';
import HeadYawMesh from '../../Meshes/Nao/HeadYaw.glb';

export default function HeadYaw(props) {
  const { nodes, materials } = useGLTF(HeadYawMesh);
  return [{geometry:nodes.HeadYaw.geometry,material:materials.HeadYawuv,scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(HeadYawMesh)
