/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei';
import LAnklePitchMesh from '../../Meshes/Nao/LAnklePitch.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(LAnklePitchMesh);
  return [{type:'raw',geometry:nodes.LAnklePitch.geometry,material:materials.RanklePitchUV,scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(LAnklePitchMesh)
