/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import RAnklePitchMesh from '../../Meshes/Nao/RAnklePitch.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RAnklePitchMesh);
  return [{type:'raw',geometry:nodes.RAnklePitch.geometry, material:materials.RAnklePitchUV, scale:[0.01, 0.01, 0.01]}]
}

useGLTF.preload(RAnklePitchMesh)
