/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import RobotiqVisual85OuterFinger from '../../../Meshes/Robotiq2f85/visual/robotiq_arg2f_85_outer_finger.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(RobotiqVisual85OuterFinger);
  return [{type:'raw', geometry:nodes.node0.geometry, material:materials['mymaterial.001']}]
}

useGLTF.preload(RobotiqVisual85OuterFinger)
