/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/link3.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.node0_001.geometry}
        material={materials.Part__Feature_001_001_001_002}
        position={[0, -0.12, 0]}
      />
      <mesh
        geometry={nodes.node1.geometry}
        material={materials.Part__Feature001_010_001_002}
        position={[0, -0.12, 0]}
      />
      <mesh
        geometry={nodes.node2.geometry}
        material={materials.Part__Feature002_007_001_002}
        position={[0, -0.12, 0]}
      />
      <mesh
        geometry={nodes.node3.geometry}
        material={materials.Part__Feature003_004_001_002}
        position={[0, -0.12, 0]}
      />
    </group>
  )
}

useGLTF.preload('/link3.glb')
